name: CI/CD Pipeline
on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-app-build
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-app-build
          path: dist/

      - name: Run tests
        run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
      
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
        

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    env:
      API_URL: ${{ github.ref == 'refs/heads/main' && 'https://api.production.com' || 'https://api.dev.com' }}
      DB_NAME: ${{ github.ref == 'refs/heads/main' && 'prod_db' || 'dev_db' }}

    steps:
      - name: Print branch-specific environment variables
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "API_URL=$API_URL"
          echo "DB_NAME=$DB_NAME"
